name: Generate docs

on:
  push:
    
  workflow_dispatch:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install -g jsdoc
      - name: Generate docs
        run: jsdoc -R README.md -d docs src/**/*
